name: CICD Pipeline for the project
on:  # On what even we want to run this workflow 
  push 
jobs:  # What are the jobs we want to run in this workflow
 buildProject: # name of job
  runs-on: ubuntu-latest  # we got a VM with ubuntu latest version
  steps:
    - name: Checkout the code 
      uses: actions/checkout@v6  # we are using the checkout action to checkout the code from the repository
    - name: Install nodejs
      uses: actions/setup-node@v6
      with:
        node-version: '18'  # we are using nodejs version 18
        cache: npm
    - name: Install dependencies for the code to run 
      run: npm ci # we are using npm ci to install the dependencies for the code to run
    - name: Run tests
      run: npm test # we are using npm test to run the tests for the code 
    - name: Build the code
      run: npm run build # we are using npm run build to build the code
    - name: Install docker
      uses: docker/setup-buildx-action@v4
    - name: build Image and push to Docker HUB 
      uses: docker/build-push-action@v6
      with:
        context: . # we are using the current directory as the context for the build
        #push: true # we want to push the image to Docker HUB
        tags: myprojectkudos01:latest # we are tagging the image with the latest tag and pushing it to Docker HUB

